<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit20ff1c40ae7fe2420af059360b446d7a
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'SpinningSquid\\' => 14,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'SpinningSquid\\' => 
        array (
            0 => __DIR__ . '/../..' . '/class',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit20ff1c40ae7fe2420af059360b446d7a::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit20ff1c40ae7fe2420af059360b446d7a::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit20ff1c40ae7fe2420af059360b446d7a::$classMap;

        }, null, ClassLoader::class);
    }
}
